package manajemen.kas;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manajemen.kas.model.User;
import manajemen.kas.dao.UserDAO;

/**
 *
 * @author ASPIRESS
 */
public class AkunForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AkunForm.class.getName());
    private int selectedId = -1;
    UserDAO userDAO = new UserDAO();

    /**
     * Creates new form AkunForm
     */
    public AkunForm() {
        initComponents();
        loadTableData();
    }

    private void navigateTo(JFrame targetFrame) {
        targetFrame.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JButton();
        btnPemasukan = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAkun = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputNamaLengkap = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelAkun = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        inputPassword = new javax.swing.JPasswordField();
        inputJabatan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Manajemen Kas | Manajemen Akun");
        setResizable(false);

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));
        Sidebar.setForeground(new java.awt.Color(255, 255, 255));
        Sidebar.setPreferredSize(new java.awt.Dimension(225, 750));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manajemen/kas/assets/AppsLogo.png"))); // NOI18N

        btnBeranda.setText("Beranda");
        btnBeranda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBeranda.setBorderPainted(false);
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnPemasukan.setText("Pemasukan");
        btnPemasukan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPemasukan.setBorderPainted(false);
        btnPemasukan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemasukanActionPerformed(evt);
            }
        });

        btnPengeluaran.setText("Pengeluaran");
        btnPengeluaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPengeluaran.setBorderPainted(false);
        btnPengeluaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manajemen/kas/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAkun.setBackground(new java.awt.Color(204, 204, 204));
        btnAkun.setText("Akun");
        btnAkun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAkun.setBorderPainted(false);
        btnAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPemasukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Logo))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(btnAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logo)
                .addGap(55, 55, 55)
                .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(null);

        jLabel2.setText("Nama Lengkap");
        Content.add(jLabel2);
        jLabel2.setBounds(30, 70, 110, 20);

        jLabel3.setText("Username");
        jLabel3.setPreferredSize(new java.awt.Dimension(45, 20));
        Content.add(jLabel3);
        jLabel3.setBounds(30, 100, 100, 20);

        jLabel4.setText("Password");
        jLabel4.setPreferredSize(new java.awt.Dimension(74, 23));
        Content.add(jLabel4);
        jLabel4.setBounds(30, 130, 100, 23);

        jLabel5.setText("Jabatan");
        Content.add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 16);
        Content.add(inputNamaLengkap);
        inputNamaLengkap.setBounds(150, 70, 480, 22);

        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        Content.add(inputUsername);
        inputUsername.setBounds(150, 100, 480, 23);

        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        Content.add(btnSimpan);
        btnSimpan.setBounds(650, 70, 90, 40);

        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        Content.add(btnHapus);
        btnHapus.setBounds(650, 120, 90, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manajemen Akun");
        Content.add(jLabel1);
        jLabel1.setBounds(20, 20, 388, 32);

        TabelAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "ID", "Nama Lengkap", "Username", "Jabatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabelAkun.getTableHeader().setReorderingAllowed(false);
        TabelAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelAkunMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelAkun);
        TabelAkun.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Content.add(jScrollPane3);
        jScrollPane3.setBounds(30, 250, 710, 480);

        jButton1.setText("Clear");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Content.add(jButton1);
        jButton1.setBounds(650, 170, 90, 40);
        Content.add(inputPassword);
        inputPassword.setBounds(150, 130, 480, 22);

        inputJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "Ketua Kelas", "Bendahara" }));
        inputJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJabatanActionPerformed(evt);
            }
        });
        Content.add(inputJabatan);
        inputJabatan.setBounds(150, 180, 480, 22);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*Kosongkan password jika tidak ingin mengubah");
        Content.add(jLabel6);
        jLabel6.setBounds(150, 150, 260, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        try {
            BerandaView beranda = new BerandaView();
            navigateTo(beranda);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemasukanActionPerformed
        // TODO add your handling code here:
        try {
            PemasukanForm pemasukan = new PemasukanForm();
            navigateTo(pemasukan);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPemasukanActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        try {
            PengeluaranForm pengeluaran = new PengeluaranForm();
            navigateTo(pengeluaran);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        try {
            LoginForm login = new LoginForm();
            navigateTo(login);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        simpanAkun();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        deleteAkun();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TabelAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelAkunMouseClicked
        // TODO add your handling code here:
        int selectedRow = TabelAkun.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        try {
            Object idValue = TabelAkun.getModel().getValueAt(selectedRow, 1);
            selectedId = Integer.parseInt(idValue.toString());

            String namaLengkap = (String) TabelAkun.getModel().getValueAt(selectedRow, 2);
            inputNamaLengkap.setText(namaLengkap);

            String username = (String) TabelAkun.getModel().getValueAt(selectedRow, 3);
            inputUsername.setText(username);

            String jabatan = (String) TabelAkun.getModel().getValueAt(selectedRow, 4);
            inputJabatan.setSelectedItem(jabatan);

            btnSimpan.setText("Update");

        } catch (NumberFormatException e) {
            System.err.println("Error saat mengambil data dari tabel: " + e.getMessage());
        }
    }//GEN-LAST:event_TabelAkunMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearInput();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJabatanActionPerformed

    private void btnAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkunActionPerformed
        // TODO add your handling code here:
        try {
            AkunForm akun = new AkunForm();
            navigateTo(akun);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form:" + e.getMessage());
        }
    }//GEN-LAST:event_btnAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AkunForm().setVisible(true));
    }

    private void loadTableData() {
        String[] columnNames = {"No.", "ID", "Nama Lengkap", "Usernamme", "Jabatan"};
        DefaultTableModel model = new DefaultTableModel(null, columnNames);
        List<User> userList = userDAO.getAll();

        int no = 1;

        for (User u : userList) {
            Object[] row = new Object[]{
                no++,
                u.getId(),
                u.getNamaLengkap(),
                u.getUsername(),
                u.getJabatan()
            };

            model.addRow(row);
        }

        TabelAkun.setModel(model);

        TabelAkun.getColumnModel().getColumn(0).setMaxWidth(40);
        TabelAkun.getColumnModel().getColumn(1).setMaxWidth(40);
    }

    private void clearInput() {
        inputNamaLengkap.setText("");
        inputUsername.setText("");
        inputPassword.setText("");
        inputJabatan.setSelectedIndex(0);

        selectedId = -1;
        btnSimpan.setText("Simpan");
    }

    private void simpanAkun() {
        String namaLengkap = inputNamaLengkap.getText();
        String username = inputUsername.getText();
        String password = String.valueOf(inputPassword.getPassword());
        String jabatan = String.valueOf(inputJabatan.getSelectedItem());

        if (namaLengkap.isEmpty() || username.isEmpty() || inputJabatan.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Nama Lengkap, Username, dan Jabatan wajib diisi.",
                    "Input Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedId == -1 && password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Password wajib diisi untuk membuat akun baru.",
                    "Input Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String finalPasswordToSet = password;

        if (selectedId != -1 && password.isEmpty()) {
            User userLama = userDAO.getUserById(selectedId);
            if (userLama != null) {
                finalPasswordToSet = userLama.getPassword();
            }
        }

        User userBaru = new User();
        userBaru.setNamaLengkap(namaLengkap);
        userBaru.setUsername(username);
        userBaru.setPassword(finalPasswordToSet);
        userBaru.setJabatan(jabatan);

        boolean sukses;

        if (selectedId != -1) {
            userBaru.setId(selectedId);
            sukses = userDAO.update(userBaru);
        } else {
            sukses = userDAO.create(userBaru);
        }

        if (!sukses) {
            JOptionPane.showMessageDialog(this,
                    "Operasi database gagal. Kemungkinan username sudah ada atau masalah koneksi.",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pesan = (selectedId != -1) ? "Data akun berhasil diperbarui." : "Akun baru berhasil didaftarkan.";
        JOptionPane.showMessageDialog(this, pesan, "Sukses", JOptionPane.INFORMATION_MESSAGE);

        clearInput();
        loadTableData();
    }

    private void deleteAkun() {
        int selectedRow = TabelAkun.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idToDelete = (int) TabelAkun.getValueAt(selectedRow, 1);
        String namaAkun = (String) TabelAkun.getValueAt(selectedRow, 3);

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus akun '" + namaAkun + "'?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean sukses = userDAO.delete(idToDelete);

            if (!sukses) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data di database.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JTable TabelAkun;
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPemasukan;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> inputJabatan;
    private javax.swing.JTextField inputNamaLengkap;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
