package manajemen.kas;

import manajemen.kas.dao.PemasukanDAO;
import manajemen.kas.model.Pemasukan;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author ASPIRESS
 */
public class PemasukanForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PemasukanForm.class.getName());

    private final PemasukanDAO pemasukanDAO = new PemasukanDAO();
    private int selectedId = -1;

    /**
     * Creates new form PemasukanForm
     */
    public PemasukanForm() {
        initComponents();
        loadTableData();
    }

    private void navigateTo(JFrame targetFrame) {
        targetFrame.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JButton();
        btnPemasukan = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAkun = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputNamaTransaksi = new javax.swing.JTextField();
        inputNominalMasuk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputKeterangan = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelPemasukan = new javax.swing.JTable();
        inputTanggal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));
        Sidebar.setForeground(new java.awt.Color(255, 255, 255));
        Sidebar.setPreferredSize(new java.awt.Dimension(225, 750));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manajemen/kas/assets/AppsLogo.png"))); // NOI18N

        btnBeranda.setText("Beranda");
        btnBeranda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBeranda.setBorderPainted(false);
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnPemasukan.setBackground(new java.awt.Color(204, 204, 204));
        btnPemasukan.setText("Pemasukan");
        btnPemasukan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPemasukan.setBorderPainted(false);
        btnPemasukan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemasukanActionPerformed(evt);
            }
        });

        btnPengeluaran.setText("Pengeluaran");
        btnPengeluaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPengeluaran.setBorderPainted(false);
        btnPengeluaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manajemen/kas/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAkun.setText("Akun");
        btnAkun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAkun.setBorderPainted(false);
        btnAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPemasukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Logo))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(btnAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logo)
                .addGap(55, 55, 55)
                .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Transaksi");
        Content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 20));

        jLabel3.setText("Tanggal");
        jLabel3.setPreferredSize(new java.awt.Dimension(45, 20));
        Content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, -1));

        jLabel4.setText("Nominal Masuk");
        jLabel4.setPreferredSize(new java.awt.Dimension(74, 23));
        Content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jLabel5.setText("Keterangan");
        Content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));
        Content.add(inputNamaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 480, -1));
        Content.add(inputNominalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 480, 23));

        inputKeterangan.setColumns(20);
        inputKeterangan.setRows(5);
        jScrollPane1.setViewportView(inputKeterangan);

        Content.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 480, 70));

        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        Content.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, 40));

        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        Content.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pencatatan Pemasukan");
        Content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 388, -1));

        TabelPemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "ID", "Nama Transaksi", "Tanggal", "Nominal", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelPemasukan.setColumnSelectionAllowed(true);
        TabelPemasukan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabelPemasukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPemasukanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelPemasukan);
        TabelPemasukan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        Content.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 710, 480));
        Content.add(inputTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 480, -1));

        jButton1.setText("Clear");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Content.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        try {
            BerandaView beranda = new BerandaView();
            navigateTo(beranda);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemasukanActionPerformed
        // TODO add your handling code here:
        try {
            PemasukanForm pemasukan = new PemasukanForm();
            navigateTo(pemasukan);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPemasukanActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        try {
            PengeluaranForm pengeluaran = new PengeluaranForm();
            navigateTo(pengeluaran);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        simpanPemasukan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        deletePemasukan();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TabelPemasukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPemasukanMouseClicked
        // TODO add your handling code here:
        int selectedRow = TabelPemasukan.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        try {
            selectedId = (int) TabelPemasukan.getModel().getValueAt(selectedRow, 1);

            String namaTransaksi = (String) TabelPemasukan.getModel().getValueAt(selectedRow, 2);
            inputNamaTransaksi.setText(namaTransaksi);

            LocalDate tanggal = (LocalDate) TabelPemasukan.getModel().getValueAt(selectedRow, 3);
            inputTanggal.setDate(java.sql.Date.valueOf(tanggal));

            String nominalFormatted = (String) TabelPemasukan.getModel().getValueAt(selectedRow, 4);
            inputNominalMasuk.setText(nominalFormatted);

            String keterangan = (String) TabelPemasukan.getModel().getValueAt(selectedRow, 5);
            inputKeterangan.setText(keterangan);

            btnSimpan.setText("Update");

        } catch (Exception e) {
            System.err.println("Error saat mengambil data dari tabel: " + e.getMessage());
        }
    }//GEN-LAST:event_TabelPemasukanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearInput();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        try {
            LoginForm login = new LoginForm();
            navigateTo(login);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkunActionPerformed
        // TODO add your handling code here:
        try {
            AkunForm akun = new AkunForm();
            navigateTo(akun);
        } catch (Exception e) {
            System.err.println("Gagal membuka Form:" + e.getMessage());
        }
    }//GEN-LAST:event_btnAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PemasukanForm().setVisible(true));
    }

    private void loadTableData() {
        String[] columnNames = {"No.", "ID", "Nama Transaksi", "Tanggal", "Nominal", "Keterangan"};

        DefaultTableModel model = new DefaultTableModel(null, columnNames);

        List<Pemasukan> listPemasukan = pemasukanDAO.getAll();

        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        symbols.setDecimalSeparator(',');
        DecimalFormat formatter = new DecimalFormat("#,##0.00", symbols); // #,##0.00 -> 1.000.000,00

        int no = 1;

        for (Pemasukan p : listPemasukan) {

            String nominalFormatted = formatter.format(p.getNominalMasuk());

            Object[] row = new Object[]{
                no++,
                p.getId(),
                p.getNamaTransaksi(),
                p.getTanggal(),
                nominalFormatted,
                p.getKeterangan()
            };

            model.addRow(row);
        }

        TabelPemasukan.setModel(model);

        TabelPemasukan.getColumnModel().getColumn(0).setMaxWidth(40);
        TabelPemasukan.getColumnModel().getColumn(1).setMaxWidth(40);
    }

    private void clearInput() {
        inputNamaTransaksi.setText("");
        inputTanggal.setDate(new Date());
        inputNominalMasuk.setText("");
        inputKeterangan.setText("");

        selectedId = -1;
        btnSimpan.setText("Simpan");
    }

    private void simpanPemasukan() {
        String namaTransaksi = inputNamaTransaksi.getText();
        java.util.Date tanggalUtilDate = inputTanggal.getDate();
        String nominalString = inputNominalMasuk.getText();
        String keterangan = inputKeterangan.getText();

        if (namaTransaksi.isEmpty() || tanggalUtilDate == null || nominalString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Transaksi, Tanggal, dan Nominal harus diisi.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate tanggal;
        BigDecimal nominalMasuk;

        try {
            tanggal = tanggalUtilDate.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            String cleanedNominalString = nominalString.replace(".", "");
            cleanedNominalString = cleanedNominalString.replace(",", ".");

            nominalMasuk = new BigDecimal(cleanedNominalString);

            if (nominalMasuk.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "Nominal harus lebih besar dari nol.", "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nominal Masuk harus berupa angka yang valid.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pemasukan pemasukanBaru = new Pemasukan();
        pemasukanBaru.setNamaTransaksi(namaTransaksi);
        pemasukanBaru.setTanggal(tanggal);
        pemasukanBaru.setNominalMasuk(nominalMasuk);
        pemasukanBaru.setKeterangan(keterangan);

        boolean sukses = true;

        if (selectedId != -1) {
            pemasukanBaru.setId(selectedId);
            sukses = pemasukanDAO.update(pemasukanBaru);
        } else {
            sukses = pemasukanDAO.create(pemasukanBaru);
        }

        if (!sukses) {
            JOptionPane.showMessageDialog(this, "Operasi database gagal. Cek log error.", "Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pesan = (selectedId != -1) ? "Data berhasil diperbarui." : "Data pemasukan berhasil disimpan.";
        JOptionPane.showMessageDialog(this, pesan, "Sukses", JOptionPane.INFORMATION_MESSAGE);

        clearInput();
        loadTableData();
    }

    private void deletePemasukan() {

        int selectedRow = TabelPemasukan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idToDelete = (int) TabelPemasukan.getValueAt(selectedRow, 1);
        String namaTransaksi = (String) TabelPemasukan.getValueAt(selectedRow, 2);

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus transaksi '" + namaTransaksi + "'?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean sukses = pemasukanDAO.delete(idToDelete);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTableData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data di database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JTable TabelPemasukan;
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPemasukan;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextArea inputKeterangan;
    private javax.swing.JTextField inputNamaTransaksi;
    private javax.swing.JTextField inputNominalMasuk;
    private com.toedter.calendar.JDateChooser inputTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
